services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5431:5432"
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin"]
      interval: 5s
      timeout: 3s
      retries: 5
    restart: unless-stopped

  wallet-api:
    build: .
    container_name: wallet-api
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/mydatabase
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_LIQUIBASE_ENABLED: true
      SERVER_PORT: 8082
    restart: on-failure

volumes:
  postgres_data:
